### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jomei** [som4ik/EMT#1]
Привет!

> Для бекенда использовать em-hiredis (или mysql2).

у тебя pgsql. Почему?

**README.rb**
1 . Описанная последовательность действий не приводит к корректному старту приложения.
2. было описать API с примерами запросов

**config/routes.rb**
1. это конфигурационный файл. Ты из конфига приложения лезешь в бизнес-логику(`DynamiceRoutes.load`), следовательно стартап приложения сломан. Нужно закомментировать эту строку чтобы просто запустить миграции при первом запуске.

**app/services/dynamice_routes.rb**

1. вместо того чтобы просто сделать  роут `get "/:short_url" => "urls_shortner#find"` ты динамически меняешь таблицу роутов в рантайме. Зачем? o__O
Это решение не только сложнее, но и error prone. Если мы запустим 2 процесса твоего приложения(А и B), пошлем запрос на запись на инстанс А, а потом пошлем запрос на чтение на инстанс B, то вместо long_url мы получим ошибку 404.

2. Тестов на этот компонент нет

**app/services/urls_shortner.rb**
1. Это сервисный объект, но он почему то хранит какой то стейт `@url` и зачем то имеет ` attr_accessor :url`
2. тестов нет

Пока решение не выглядит готовым к ревью со стороны.
Вопросы можно задавать прямо в этой issue.
Исправления можно оформить отдельным PR и пингануть в нем меня. 
Успехов!

**Comment by som4ik** [comment]
@jomei  
please have a look https://github.com/som4ik/EMT/pull/2 
spent time ~ 1.5 h
